# Generated by Django 5.0.1 on 2024-02-15 10:28

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', tinymce.models.HTMLField()),
                ('imagem', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
